version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - my_network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - my_network
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    networks:
      - my_network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - prometheus_data:/prometheus
    networks:
      - my_network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

volumes:
  mysql_data:
  prometheus_data:

networks:
  my_network:
    external: true
